version: "3.1"

services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    user: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: xyz
      POSTGRES_USER: alice
      POSTGRES_DB: calculation
    command: ["postgres"]
    volumes:
      - api_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  api:
    image: api
    restart: always
    build:
      context: ./API
    container_name: api
    ports:
      - 8001:8000
    depends_on:
      - db
    environment:
      DATABASE: "postgresql://alice:xyz@postgres:5432/calculation"
      CALCULATOR_URL: "http://calculator:8000"

  calculator:
    image: calculator
    depends_on:
      - api
    build:
      context: "./Calculation"

    ports:
      - 8002:8000

    restart: always
    container_name: calculator

volumes:
  api_data:
    external: true
